# permissions for end users to edit wps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: wp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: wp
    app.kubernetes.io/part-of: wp
    app.kubernetes.io/managed-by: kustomize
  name: wp-editor-role
rules:
- apiGroups:
  - wp.gurasan.github.io
  resources:
  - wps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wp.gurasan.github.io
  resources:
  - wps/status
  verbs:
  - get
